create-messages-table=CREATE TABLE IF NOT EXISTS messages (id SERIAL PRIMARY KEY, sender VARCHAR(255) UNIQUE, content TEXT)
create-message=INSERT INTO messages (sender, content) VALUES ($1, $2)
all-messages=SELECT * FROM messages
