create-messages-table=CREATE TABLE IF NOT EXISTS messages (id INTEGER IDENTITY PRIMARY KEY,sender VARCHAR(255) UNIQUE, content CLOB)
create-message=INSERT INTO messages (sender, message) VALUES ($1, $2)
all-messages=SELECT * FROM messages
