create-messages-table=CREATE TABLE IF NOT EXISTS messages (id SERIAL PRIMARY KEY, sender VARCHAR(255), content TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP, is_deleted BOOLEAN DEFAULT FALSE)
create-message=INSERT INTO messages (sender, content) VALUES ($1, $2)
all-messages=SELECT * FROM (SELECT * FROM messages WHERE is_deleted = FALSE ORDER BY id DESC LIMIT 20) sub ORDER BY id ASC;
update-message=UPDATE messages SET content = $1, updated_at = NOW() WHERE id = $2 AND is_deleted = FALSE RETURNING updated_at
delete-message=DELETE FROM messages WHERE id = $1
